// Contexten voor vraagstukjes en referentiematen. Dit bestand mag je gerust aanpassen of uitbreiden.
//
// lengte: { onderwerp: 'een slang', bepaald: 'de slang', dim: 'lang', cm: [min, max] }
//   - onderwerp: met 'een' (voor "Een slang is ... lang."), bepaald: met 'de' of 'het' (voor antwoorden)
//   - dim: 'lang', 'hoog' of 'breed' (bepaalt ook "het langst/hoogst/breedst")
//   - cm: realistische lengte in centimeter (de generator kiest een getal binnen dit bereik)

export const THEMAS = {
  dieren: {
    naam: 'Dieren',
    lengte: [
      { onderwerp: 'een slang', bepaald: 'de slang', dim: 'lang', cm: [50, 300] },
      { onderwerp: 'een krokodil', bepaald: 'de krokodil', dim: 'lang', cm: [200, 500] },
      { onderwerp: 'een giraf', bepaald: 'de giraf', dim: 'hoog', cm: [400, 550] },
      { onderwerp: 'een olifant', bepaald: 'de olifant', dim: 'hoog', cm: [250, 350] },
      { onderwerp: 'een muis', bepaald: 'de muis', dim: 'lang', cm: [5, 10] },
      { onderwerp: 'een konijn', bepaald: 'het konijn', dim: 'lang', cm: [30, 50] },
    ],
    massa: [
      { onderwerp: 'een muis', bepaald: 'de muis', g: [20, 40] },
      { onderwerp: 'een konijn', bepaald: 'het konijn', g: [1000, 2000] },
      { onderwerp: 'een kip', bepaald: 'de kip', g: [2000, 3000] },
      { onderwerp: 'een hond', bepaald: 'de hond', g: [5000, 30000] },
      { onderwerp: 'een olifant', bepaald: 'de olifant', g: [3000000, 6000000] },
    ],
    tijd: [
      { onderwerp: 'de wandeling met de hond', bepaald: 'de wandeling met de hond', min: [20, 60] },
      { onderwerp: 'het voeren van de dieren', bepaald: 'het voeren van de dieren', min: [10, 30] },
      { onderwerp: 'het bezoek aan de dierentuin', bepaald: 'het bezoek aan de dierentuin', min: [120, 300] },
      { onderwerp: 'de winterslaap van de egel', bepaald: 'de winterslaap van de egel', min: [129600, 172800] },
    ],
    geld: [
      { onderwerp: 'een zak hondenvoer', bepaald: 'de zak hondenvoer', cent: [800, 2000] },
      { onderwerp: 'een speelbal voor de hond', bepaald: 'de speelbal', cent: [200, 500] },
      { onderwerp: 'een halsband', bepaald: 'de halsband', cent: [500, 1500] },
      { onderwerp: 'een bakje visvoer', bepaald: 'het bakje visvoer', cent: [150, 400] },
      { onderwerp: 'een kooi', bepaald: 'de kooi', cent: [2000, 6000] },
    ],
    dingen: ['eendjes', 'visjes', 'konijnen', 'kuikens'],
    bakken: ['hokken', 'kooien'],
  },
  speelplaats: {
    naam: 'Speelplaats',
    lengte: [
      { onderwerp: 'een glijbaan', bepaald: 'de glijbaan', dim: 'lang', cm: [200, 400] },
      { onderwerp: 'een springtouw', bepaald: 'het springtouw', dim: 'lang', cm: [200, 300] },
      { onderwerp: 'een zandbak', bepaald: 'de zandbak', dim: 'breed', cm: [200, 400] },
      { onderwerp: 'een speelplaats', bepaald: 'de speelplaats', dim: 'lang', cm: [2000, 5000] },
      { onderwerp: 'een bank', bepaald: 'de bank', dim: 'lang', cm: [150, 250] },
    ],
    massa: [
      { onderwerp: 'een bal', bepaald: 'de bal', g: [300, 500] },
      { onderwerp: 'een schooltas', bepaald: 'de schooltas', g: [3000, 8000] },
      { onderwerp: 'een springtouw', bepaald: 'het springtouw', g: [100, 300] },
      { onderwerp: 'een fles water', bepaald: 'de fles water', g: [500, 1500] },
      { onderwerp: 'een boterham', bepaald: 'de boterham', g: [50, 100] },
    ],
    tijd: [
      { onderwerp: 'de speeltijd', bepaald: 'de speeltijd', min: [15, 20] },
      { onderwerp: 'een potje voetbal', bepaald: 'het potje voetbal', min: [10, 40] },
      { onderwerp: 'de middagpauze', bepaald: 'de middagpauze', min: [45, 75] },
      { onderwerp: 'een spelletje verstoppertje', bepaald: 'het spelletje verstoppertje', min: [10, 30] },
    ],
    geld: [
      { onderwerp: 'een ijsje', bepaald: 'het ijsje', cent: [100, 300] },
      { onderwerp: 'een springtouw', bepaald: 'het springtouw', cent: [300, 800] },
      { onderwerp: 'een bal', bepaald: 'de bal', cent: [300, 1000] },
      { onderwerp: 'een knikker', bepaald: 'de knikker', cent: [10, 50] },
      { onderwerp: 'een pak koekjes', bepaald: 'het pak koekjes', cent: [150, 300] },
    ],
    dingen: ['knikkers', 'ballen', 'stickers', 'springtouwen'],
    bakken: ['zakjes', 'dozen'],
  },
  keuken: {
    naam: 'Keuken',
    lengte: [
      { onderwerp: 'een lepel', bepaald: 'de lepel', dim: 'lang', cm: [15, 25] },
      { onderwerp: 'een bakplaat', bepaald: 'de bakplaat', dim: 'lang', cm: [30, 45] },
      { onderwerp: 'een keukentafel', bepaald: 'de keukentafel', dim: 'lang', cm: [120, 200] },
      { onderwerp: 'een koelkast', bepaald: 'de koelkast', dim: 'hoog', cm: [150, 190] },
      { onderwerp: 'een wortel', bepaald: 'de wortel', dim: 'lang', cm: [10, 25] },
    ],
    massa: [
      { onderwerp: 'een appel', bepaald: 'de appel', g: [150, 250] },
      { onderwerp: 'een ei', bepaald: 'het ei', g: [50, 70] },
      { onderwerp: 'een brood', bepaald: 'het brood', g: [500, 900] },
      { onderwerp: 'een pak suiker', bepaald: 'het pak suiker', g: [1000, 1000] },
      { onderwerp: 'een pak meel', bepaald: 'het pak meel', g: [1000, 2000] },
    ],
    tijd: [
      { onderwerp: 'het koken van een ei', bepaald: 'het koken van een ei', min: [6, 10] },
      { onderwerp: 'het koken van de pasta', bepaald: 'het koken van de pasta', min: [8, 12] },
      { onderwerp: 'het bakken van de taart', bepaald: 'het bakken van de taart', min: [30, 60] },
      { onderwerp: 'de afwas', bepaald: 'de afwas', min: [10, 20] },
    ],
    geld: [
      { onderwerp: 'een brood', bepaald: 'het brood', cent: [200, 400] },
      { onderwerp: 'een liter melk', bepaald: 'de liter melk', cent: [100, 200] },
      { onderwerp: 'een pak spaghetti', bepaald: 'het pak spaghetti', cent: [100, 250] },
      { onderwerp: 'een kilo appels', bepaald: 'de kilo appels', cent: [200, 400] },
      { onderwerp: 'een pot jam', bepaald: 'de pot jam', cent: [200, 350] },
    ],
    dingen: ['eieren', 'appels', 'koekjes', 'wortels'],
    bakken: ['schaaltjes', 'dozen'],
  },
  sprookjes: {
    naam: 'Sprookjes',
    lengte: [
      { onderwerp: 'een bonenstaak', bepaald: 'de bonenstaak', dim: 'hoog', cm: [2000, 5000] },
      { onderwerp: 'de toren van Rapunzel', bepaald: 'de toren van Rapunzel', dim: 'hoog', cm: [1500, 3000] },
      { onderwerp: 'de neus van Pinokkio', bepaald: 'de neus van Pinokkio', dim: 'lang', cm: [20, 100] },
      { onderwerp: 'een tovenaarsstaf', bepaald: 'de tovenaarsstaf', dim: 'lang', cm: [150, 200] },
      { onderwerp: 'de mantel van de koning', bepaald: 'de mantel van de koning', dim: 'lang', cm: [150, 300] },
    ],
    massa: [
      { onderwerp: 'de appel van Sneeuwwitje', bepaald: 'de appel van Sneeuwwitje', g: [150, 300] },
      { onderwerp: 'de zak met gouden munten', bepaald: 'de zak met gouden munten', g: [2000, 8000] },
      { onderwerp: 'de pot honing van Winnie', bepaald: 'de pot honing van Winnie', g: [500, 1000] },
      { onderwerp: 'de kroon van de koning', bepaald: 'de kroon van de koning', g: [1000, 3000] },
      { onderwerp: 'de glazen muiltjes', bepaald: 'de glazen muiltjes', g: [300, 500] },
    ],
    tijd: [
      { onderwerp: 'het bal van Assepoester', bepaald: 'het bal van Assepoester', min: [240, 360] },
      { onderwerp: 'de reis door het bos', bepaald: 'de reis door het bos', min: [120, 300] },
      { onderwerp: 'het voorlezen van het sprookje', bepaald: 'het voorlezen van het sprookje', min: [10, 20] },
      { onderwerp: 'de wandeling naar het huisje van de heks', bepaald: 'de wandeling naar het huisje van de heks', min: [30, 90] },
    ],
    geld: [
      { onderwerp: 'een toverstaf', bepaald: 'de toverstaf', cent: [500, 1500] },
      { onderwerp: 'een kroon', bepaald: 'de kroon', cent: [500, 2000] },
      { onderwerp: 'een tovermantel', bepaald: 'de tovermantel', cent: [2000, 5000] },
      { onderwerp: 'een appel', bepaald: 'de appel', cent: [50, 150] },
      { onderwerp: 'een toverboek', bepaald: 'het toverboek', cent: [800, 2000] },
    ],
    dingen: ['gouden munten', 'bloemen', 'sterren', 'appels'],
    bakken: ['kistjes', 'manden'],
  },
  winkel: {
    naam: 'Winkel',
    lengte: [
      { onderwerp: 'een lint', bepaald: 'het lint', dim: 'lang', cm: [50, 300] },
      { onderwerp: 'een toonbank', bepaald: 'de toonbank', dim: 'lang', cm: [150, 300] },
      { onderwerp: 'een stuk stof', bepaald: 'het stuk stof', dim: 'lang', cm: [100, 400] },
      { onderwerp: 'een winkelrek', bepaald: 'het winkelrek', dim: 'hoog', cm: [100, 250] },
      { onderwerp: 'een broodplank', bepaald: 'de broodplank', dim: 'lang', cm: [30, 60] },
    ],
    massa: [
      { onderwerp: 'een zak aardappelen', bepaald: 'de zak aardappelen', g: [2000, 5000] },
      { onderwerp: 'een pak melk', bepaald: 'het pak melk', g: [1000, 1000] },
      { onderwerp: 'een zak snoep', bepaald: 'de zak snoep', g: [200, 500] },
      { onderwerp: 'een meloen', bepaald: 'de meloen', g: [1000, 2000] },
      { onderwerp: 'een brood', bepaald: 'het brood', g: [500, 900] },
    ],
    tijd: [
      { onderwerp: 'het winkelen', bepaald: 'het winkelen', min: [30, 120] },
      { onderwerp: 'de rij aan de kassa', bepaald: 'de rij aan de kassa', min: [3, 10] },
      { onderwerp: 'het inpakken van een cadeau', bepaald: 'het inpakken van een cadeau', min: [5, 15] },
      { onderwerp: 'de opendeurdag', bepaald: 'de opendeurdag', min: [240, 480] },
    ],
    geld: [
      { onderwerp: 'een lolly', bepaald: 'de lolly', cent: [30, 100] },
      { onderwerp: 'een boek', bepaald: 'het boek', cent: [800, 2000] },
      { onderwerp: 'een pen', bepaald: 'de pen', cent: [100, 300] },
      { onderwerp: 'een t-shirt', bepaald: 'het t-shirt', cent: [800, 2500] },
      { onderwerp: 'een rugzak', bepaald: 'de rugzak', cent: [1500, 4000] },
    ],
    dingen: ['ballonnen', 'potloden', 'lolly’s', 'boeken'],
    bakken: ['dozen', 'zakken'],
  },
  sport: {
    naam: 'Sport',
    lengte: [
      { onderwerp: 'een voetbaldoel', bepaald: 'het voetbaldoel', dim: 'breed', cm: [500, 750] },
      { onderwerp: 'een zwembad', bepaald: 'het zwembad', dim: 'lang', cm: [2500, 5000] },
      { onderwerp: 'een tennisracket', bepaald: 'het tennisracket', dim: 'lang', cm: [60, 70] },
      { onderwerp: 'een hoogspringlat', bepaald: 'de hoogspringlat', dim: 'lang', cm: [300, 400] },
      { onderwerp: 'een basketbalpaal', bepaald: 'de basketbalpaal', dim: 'hoog', cm: [300, 400] },
    ],
    massa: [
      { onderwerp: 'een voetbal', bepaald: 'de voetbal', g: [400, 450] },
      { onderwerp: 'een tennisbal', bepaald: 'de tennisbal', g: [55, 60] },
      { onderwerp: 'een basketbal', bepaald: 'de basketbal', g: [600, 650] },
      { onderwerp: 'een trofee', bepaald: 'de trofee', g: [1000, 3000] },
      { onderwerp: 'een sporttas', bepaald: 'de sporttas', g: [3000, 8000] },
    ],
    tijd: [
      { onderwerp: 'de voetbalmatch', bepaald: 'de voetbalmatch', min: [80, 100] },
      { onderwerp: 'de zwemles', bepaald: 'de zwemles', min: [30, 60] },
      { onderwerp: 'de opwarming', bepaald: 'de opwarming', min: [10, 20] },
      { onderwerp: 'de turnles', bepaald: 'de turnles', min: [45, 90] },
    ],
    geld: [
      { onderwerp: 'een voetbal', bepaald: 'de voetbal', cent: [1000, 3000] },
      { onderwerp: 'een tennisbal', bepaald: 'de tennisbal', cent: [100, 300] },
      { onderwerp: 'een sporttas', bepaald: 'de sporttas', cent: [2000, 5000] },
      { onderwerp: 'een zwembril', bepaald: 'de zwembril', cent: [1000, 2000] },
      { onderwerp: 'een springtouw', bepaald: 'het springtouw', cent: [500, 1000] },
    ],
    dingen: ['ballen', 'shirts', 'medailles', 'petten'],
    bakken: ['tassen', 'dozen'],
  },
  boerderij: {
    naam: 'Boerderij',
    lengte: [
      { onderwerp: 'een stal', bepaald: 'de stal', dim: 'lang', cm: [1000, 3000] },
      { onderwerp: 'een tractor', bepaald: 'de tractor', dim: 'lang', cm: [300, 600] },
      { onderwerp: 'een koe', bepaald: 'de koe', dim: 'lang', cm: [200, 300] },
      { onderwerp: 'een hek', bepaald: 'het hek', dim: 'lang', cm: [300, 1000] },
      { onderwerp: 'een strobaal', bepaald: 'de strobaal', dim: 'lang', cm: [100, 150] },
    ],
    massa: [
      { onderwerp: 'een kip', bepaald: 'de kip', g: [2000, 3000] },
      { onderwerp: 'een ei', bepaald: 'het ei', g: [50, 70] },
      { onderwerp: 'een big', bepaald: 'de big', g: [20000, 100000] },
      { onderwerp: 'een zak voer', bepaald: 'de zak voer', g: [10000, 25000] },
      { onderwerp: 'een koe', bepaald: 'de koe', g: [500000, 700000] },
    ],
    tijd: [
      { onderwerp: 'het melken van de koeien', bepaald: 'het melken van de koeien', min: [30, 60] },
      { onderwerp: 'de rit met de tractor', bepaald: 'de rit met de tractor', min: [20, 90] },
      { onderwerp: 'het voeren van de kippen', bepaald: 'het voeren van de kippen', min: [10, 20] },
      { onderwerp: 'de oogst', bepaald: 'de oogst', min: [4320, 14400] },
    ],
    geld: [
      { onderwerp: 'een zak voer', bepaald: 'de zak voer', cent: [1500, 3000] },
      { onderwerp: 'een bos wortels', bepaald: 'de bos wortels', cent: [150, 300] },
      { onderwerp: 'een pot honing', bepaald: 'de pot honing', cent: [300, 600] },
      { onderwerp: 'een dozijn eieren', bepaald: 'het dozijn eieren', cent: [200, 400] },
      { onderwerp: 'een liter verse melk', bepaald: 'de liter verse melk', cent: [80, 150] },
    ],
    dingen: ['kippen', 'eieren', 'appels', 'lammetjes'],
    bakken: ['manden', 'kratten'],
  },
  school: {
    naam: 'School',
    lengte: [
      { onderwerp: 'een klas', bepaald: 'de klas', dim: 'lang', cm: [600, 1000] },
      { onderwerp: 'een schoolbord', bepaald: 'het schoolbord', dim: 'breed', cm: [200, 400] },
      { onderwerp: 'een potlood', bepaald: 'het potlood', dim: 'lang', cm: [15, 20] },
      { onderwerp: 'een liniaal', bepaald: 'de liniaal', dim: 'lang', cm: [20, 30] },
      { onderwerp: 'een gang', bepaald: 'de gang', dim: 'lang', cm: [1000, 3000] },
    ],
    massa: [
      { onderwerp: 'een schrift', bepaald: 'het schrift', g: [80, 150] },
      { onderwerp: 'een boek', bepaald: 'het boek', g: [200, 600] },
      { onderwerp: 'een schooltas', bepaald: 'de schooltas', g: [3000, 8000] },
      { onderwerp: 'een pen', bepaald: 'de pen', g: [10, 20] },
      { onderwerp: 'een rekenmachine', bepaald: 'de rekenmachine', g: [100, 200] },
    ],
    tijd: [
      { onderwerp: 'de les wiskunde', bepaald: 'de les wiskunde', min: [45, 50] },
      { onderwerp: 'de schooldag', bepaald: 'de schooldag', min: [360, 420] },
      { onderwerp: 'de speeltijd', bepaald: 'de speeltijd', min: [15, 20] },
      { onderwerp: 'de zomervakantie', bepaald: 'de zomervakantie', min: [86400, 100800] },
    ],
    geld: [
      { onderwerp: 'een schrift', bepaald: 'het schrift', cent: [100, 300] },
      { onderwerp: 'een potlood', bepaald: 'het potlood', cent: [30, 100] },
      { onderwerp: 'een gom', bepaald: 'de gom', cent: [30, 100] },
      { onderwerp: 'een boekentas', bepaald: 'de boekentas', cent: [1500, 4000] },
      { onderwerp: 'een lunchbox', bepaald: 'de lunchbox', cent: [500, 1500] },
    ],
    dingen: ['boeken', 'potloden', 'stiften', 'schriften'],
    bakken: ['bakken', 'dozen'],
  },
};

export const THEMA_KEUZES = [['gemengd', 'Gemengd'], ...Object.entries(THEMAS).map(([k, t]) => [k, t.naam])];

// Namen voor kinderen in de zinnen.
export const NAMEN = ['Anna', 'Bram', 'Chloë', 'Daan', 'Emma', 'Finn', 'Lotte', 'Milan', 'Noor', 'Sam', 'Yara', 'Jens'];

// Referentiematen: "Een potlood is ongeveer 18 cm lang." (getal en eenheid zijn wat een mens zou zeggen)
export const REFERENTIE_LENGTE = [
  { onderwerp: 'een potlood', dim: 'lang', getal: 18, eenheid: 'cm', thema: 'school' },
  { onderwerp: 'een liniaal', dim: 'lang', getal: 30, eenheid: 'cm', thema: 'school' },
  { onderwerp: 'een deur', dim: 'hoog', getal: 2, eenheid: 'm', thema: 'school' },
  { onderwerp: 'een klas', dim: 'lang', getal: 8, eenheid: 'm', thema: 'school' },
  { onderwerp: 'een gang', dim: 'lang', getal: 20, eenheid: 'm', thema: 'school' },
  { onderwerp: 'een schooltafel', dim: 'breed', getal: 7, eenheid: 'dm', thema: 'school' },
  { onderwerp: 'een hand', dim: 'breed', getal: 1, eenheid: 'dm', thema: 'dieren' },
  { onderwerp: 'een giraf', dim: 'hoog', getal: 5, eenheid: 'm', thema: 'dieren' },
  { onderwerp: 'een muis', dim: 'lang', getal: 8, eenheid: 'cm', thema: 'dieren' },
  { onderwerp: 'een slang', dim: 'lang', getal: 2, eenheid: 'm', thema: 'dieren' },
  { onderwerp: 'een konijn', dim: 'lang', getal: 4, eenheid: 'dm', thema: 'dieren' },
  { onderwerp: 'een glijbaan', dim: 'lang', getal: 3, eenheid: 'm', thema: 'speelplaats' },
  { onderwerp: 'een speelplaats', dim: 'lang', getal: 40, eenheid: 'm', thema: 'speelplaats' },
  { onderwerp: 'een springtouw', dim: 'lang', getal: 25, eenheid: 'dm', thema: 'speelplaats' },
  { onderwerp: 'een lepel', dim: 'lang', getal: 20, eenheid: 'cm', thema: 'keuken' },
  { onderwerp: 'een koelkast', dim: 'hoog', getal: 17, eenheid: 'dm', thema: 'keuken' },
  { onderwerp: 'een keukentafel', dim: 'lang', getal: 15, eenheid: 'dm', thema: 'keuken' },
  { onderwerp: 'een tennisracket', dim: 'lang', getal: 68, eenheid: 'cm', thema: 'sport' },
  { onderwerp: 'een zwembad', dim: 'lang', getal: 25, eenheid: 'm', thema: 'sport' },
  { onderwerp: 'een voetbalveld', dim: 'lang', getal: 100, eenheid: 'm', thema: 'sport' },
  { onderwerp: 'een koe', dim: 'lang', getal: 25, eenheid: 'dm', thema: 'boerderij' },
  { onderwerp: 'een tractor', dim: 'lang', getal: 4, eenheid: 'm', thema: 'boerderij' },
  { onderwerp: 'een strobaal', dim: 'lang', getal: 12, eenheid: 'dm', thema: 'boerderij' },
  { onderwerp: 'een tovenaarsstaf', dim: 'lang', getal: 18, eenheid: 'dm', thema: 'sprookjes' },
  { onderwerp: 'de bonenstaak van Jack', dim: 'hoog', getal: 30, eenheid: 'm', thema: 'sprookjes' },
  { onderwerp: 'een lint', dim: 'lang', getal: 2, eenheid: 'm', thema: 'winkel' },
  { onderwerp: 'een toonbank', dim: 'lang', getal: 2, eenheid: 'm', thema: 'winkel' },
  { onderwerp: 'een broodplank', dim: 'lang', getal: 45, eenheid: 'cm', thema: 'winkel' },
  { onderwerp: 'de weg naar school', dim: 'lang', getal: 2, eenheid: 'km', thema: 'school' },
  { onderwerp: 'een bruggetje over de beek', dim: 'lang', getal: 5, eenheid: 'm', thema: 'boerderij' },
];

export const REFERENTIE_MASSA = [
  { onderwerp: 'een appel', getal: 150, eenheid: 'g', thema: 'keuken' },
  { onderwerp: 'een ei', getal: 60, eenheid: 'g', thema: 'keuken' },
  { onderwerp: 'een brood', getal: 800, eenheid: 'g', thema: 'winkel' },
  { onderwerp: 'een zak aardappelen', getal: 5, eenheid: 'kg', thema: 'winkel' },
  { onderwerp: 'een pak suiker', getal: 1, eenheid: 'kg', thema: 'keuken' },
  { onderwerp: 'een pen', getal: 15, eenheid: 'g', thema: 'school' },
  { onderwerp: 'een schooltas', getal: 5, eenheid: 'kg', thema: 'school' },
  { onderwerp: 'een boek', getal: 400, eenheid: 'g', thema: 'school' },
  { onderwerp: 'een muis', getal: 30, eenheid: 'g', thema: 'dieren' },
  { onderwerp: 'een hond', getal: 20, eenheid: 'kg', thema: 'dieren' },
  { onderwerp: 'een konijn', getal: 2, eenheid: 'kg', thema: 'dieren' },
  { onderwerp: 'een voetbal', getal: 430, eenheid: 'g', thema: 'sport' },
  { onderwerp: 'een tennisbal', getal: 58, eenheid: 'g', thema: 'sport' },
  { onderwerp: 'een koe', getal: 600, eenheid: 'kg', thema: 'boerderij' },
  { onderwerp: 'een big', getal: 50, eenheid: 'kg', thema: 'boerderij' },
  { onderwerp: 'de zak met gouden munten', getal: 4, eenheid: 'kg', thema: 'sprookjes' },
  { onderwerp: 'de appel van Sneeuwwitje', getal: 200, eenheid: 'g', thema: 'sprookjes' },
  { onderwerp: 'een bal', getal: 400, eenheid: 'g', thema: 'speelplaats' },
];

export const REFERENTIE_TIJD = [
  { onderwerp: 'de speeltijd', getal: 15, eenheid: 'min', thema: 'speelplaats' },
  { onderwerp: 'de middagpauze', getal: 1, eenheid: 'uur', thema: 'speelplaats' },
  { onderwerp: 'de les wiskunde', getal: 50, eenheid: 'min', thema: 'school' },
  { onderwerp: 'de schooldag', getal: 6, eenheid: 'uur', thema: 'school' },
  { onderwerp: 'de zomervakantie', getal: 60, eenheid: 'dag', thema: 'school' },
  { onderwerp: 'het koken van een ei', getal: 8, eenheid: 'min', thema: 'keuken' },
  { onderwerp: 'het bakken van de taart', getal: 1, eenheid: 'uur', thema: 'keuken' },
  { onderwerp: 'de voetbalmatch', getal: 90, eenheid: 'min', thema: 'sport' },
  { onderwerp: 'de zwemles', getal: 45, eenheid: 'min', thema: 'sport' },
  { onderwerp: 'de wandeling met de hond', getal: 30, eenheid: 'min', thema: 'dieren' },
  { onderwerp: 'het bezoek aan de dierentuin', getal: 4, eenheid: 'uur', thema: 'dieren' },
  { onderwerp: 'het melken van de koeien', getal: 45, eenheid: 'min', thema: 'boerderij' },
  { onderwerp: 'de oogst', getal: 7, eenheid: 'dag', thema: 'boerderij' },
  { onderwerp: 'het bal van Assepoester', getal: 5, eenheid: 'uur', thema: 'sprookjes' },
  { onderwerp: 'het voorlezen van het sprookje', getal: 15, eenheid: 'min', thema: 'sprookjes' },
  { onderwerp: 'de rij aan de kassa', getal: 5, eenheid: 'min', thema: 'winkel' },
  { onderwerp: 'een knipoog', getal: 1, eenheid: 's', thema: 'speelplaats' },
  { onderwerp: 'tanden poetsen', getal: 120, eenheid: 's', thema: 'school' },
];

export const REFERENTIE_GELD = [
  { onderwerp: 'een ijsje', getal: 2, eenheid: 'euro', thema: 'speelplaats' },
  { onderwerp: 'een knikker', getal: 20, eenheid: 'cent', thema: 'speelplaats' },
  { onderwerp: 'een potlood', getal: 50, eenheid: 'cent', thema: 'school' },
  { onderwerp: 'een boekentas', getal: 30, eenheid: 'euro', thema: 'school' },
  { onderwerp: 'een brood', getal: 3, eenheid: 'euro', thema: 'keuken' },
  { onderwerp: 'een liter melk', getal: 120, eenheid: 'cent', thema: 'keuken' },
  { onderwerp: 'een lolly', getal: 50, eenheid: 'cent', thema: 'winkel' },
  { onderwerp: 'een boek', getal: 12, eenheid: 'euro', thema: 'winkel' },
  { onderwerp: 'een voetbal', getal: 20, eenheid: 'euro', thema: 'sport' },
  { onderwerp: 'een tennisbal', getal: 2, eenheid: 'euro', thema: 'sport' },
  { onderwerp: 'een zak hondenvoer', getal: 15, eenheid: 'euro', thema: 'dieren' },
  { onderwerp: 'een kooi', getal: 40, eenheid: 'euro', thema: 'dieren' },
  { onderwerp: 'een dozijn eieren', getal: 3, eenheid: 'euro', thema: 'boerderij' },
  { onderwerp: 'een toverstaf', getal: 10, eenheid: 'euro', thema: 'sprookjes' },
  { onderwerp: 'een appel', getal: 80, eenheid: 'cent', thema: 'sprookjes' },
];
